---

- hosts: all
  gather_facts: |
    {{ gather_facts | default(True) }}
  vars:
    fix_bash_bug_proxy: # http://proxy.domain.tld:3128
  roles:
    - role: thydel.runp
    - role: thydel.version-ansible
    - role: thydel.patch
    - role: thydel.fix-bash-bug
