---

- include: update.yml tags=update

- include: newer.yml tags=newer
  when:
    ansible_distribution == 'Debian'
    and ansible_distribution_major_version|int >= 6
    or ansible_distribution == 'Ubuntu'
    and ansible_distribution_major_version|int >= 12

- include: lenny.yml tags=lenny
  when:
    ansible_distribution == 'Debian'
    and ansible_distribution_major_version|int == 5

- include: check.yml tags=check
