---

- when:
    ansible_distribution == 'Debian'
    and ansible_distribution_major_version|int == 6
  with_items:
    - deb http://http.debian.net/debian squeeze-lts main contrib non-free
    - deb-src http://http.debian.net/debian squeeze-lts main contrib non-free
  apt_repository: 
    repo="{{ item }}"
  name: fix-bash-bug - squeeze - add squeeze-lts repository

- when:
    ansible_distribution == 'Debian'
    and ansible_distribution_major_version|int >= 6
    or ansible_distribution == 'Ubuntu'
    and ansible_distribution_major_version|int >= 12
  apt:
    name=bash
    state=latest
    update_cache=yes
    cache_valid_time={{ fix_bash_bug_proxy_cache_valid_time }}
  name: fix-bash-bug - squeeze, wheezy, ubuntu - update bash
